#!/usr/bin/env bash
# ============================================================================
# 红区测试: 6 个 weapon head position 循环夹取 + torque docking
# 启动链路: Arduino sensor → global navigation → local/arm control → Damiao/Arduino actuators
# ============================================================================

WS=~/Robocon2026_r2/2026R2_ws
TOOLS=$WS/tools
DAMIAO_GEAR_RATIO=19.227
CHASSIS_CAN_DEVICE="${CHASSIS_CAN_DEVICE:-/dev/chassis_damiao_can}"
ARM_ARDUINO_PORT="${ARM_ARDUINO_PORT:-/dev/arm_arduino}"
PLOT_DEBUG_HEADLESS="${PLOT_DEBUG_HEADLESS:-0}"
PLOT_MAX_HISTORY="${PLOT_MAX_HISTORY:-600}"
PLOT_UPDATE_RATE_HZ="${PLOT_UPDATE_RATE_HZ:-10.0}"
PLOT_SAVE_DIR="${PLOT_SAVE_DIR:-/home/robotics/Robocon2026_r2/log_plot_debug}"
MISSION_FILE=/tmp/red_area_mission.yaml
FIELD_FILE=$WS/src/navigation/routes/red_field.yaml
MIRROR_Y=false

if [ ! -e "$CHASSIS_CAN_DEVICE" ] && [ "$CHASSIS_CAN_DEVICE" = "/dev/chassis_damiao_can" ] && [ -e "/dev/damiao_can" ]; then
  CHASSIS_CAN_DEVICE="/dev/damiao_can"
fi

source "$WS/install/setup.bash"

echo "[red_area] weapon rack cycle: weapon1/#1 -> slots 1..6, pickup -> docking -> next, stop after 5 successes。"
echo "[red_area] chassis USB-CAN: $CHASSIS_CAN_DEVICE"
echo "[red_area] arm Arduino: $ARM_ARDUINO_PORT"
echo ""

if [ ! -e "$CHASSIS_CAN_DEVICE" ]; then
  echo "[red_area] WARNING: $CHASSIS_CAN_DEVICE 不存在，damiao_ctrl 窗口会启动但 chassis 组不会 active。"
  echo "[red_area] 请检查 USB-CAN 是否接入，或先安装/刷新 2026R2_ws/99-robocon-r2.rules。"
  echo ""
fi

if [ ! -e "$ARM_ARDUINO_PORT" ]; then
  echo "[red_area] WARNING: $ARM_ARDUINO_PORT 不存在，arm_arduino_node 会等待/重连，gripper 可能不会实际动作。"
  echo ""
fi

# ---- 清理所有残留进程 ----
echo "[red_area] 清理残留进程..."
bash "$TOOLS/cleanup_ros2.sh" --force 2>&1 | grep -E "killed|完成|空闲|残留|无相关" || true
sleep 0.5
# cleanup 会 stop daemon；提前 restart 避免 ros2 run 首次 discovery 太慢
ros2 daemon start 2>/dev/null || true
echo ""

cat > "$MISSION_FILE" <<EOF
version: 1
frame_id: map
angle_unit: deg

# Red Area FSM: weapon1/#1 starts a six-position rack cycle.
# The cycle stops after five successful pickups+dockings or after all six slots are processed.
waypoints:
  wp_weapon_1:
    # #1 is the weapon1 position. Slots 2..6 are generated by slot_spacing_m along slot_direction_rad.
    pose: { x: 0.35, y: 0.85, yaw: 0.0 }
    pos_tolerance: 0.005
    yaw_tolerance_deg: 1.0

profiles:
  red_area:
    speed_mps: 0.4
    yaw_rate_rps: 0.3
    start_radius_m: 0.0
    end_radius_m: 0.0
    min_speed_scale: 0.0
    k_p_x: 0.081
    k_p_y: 0.115
    k_i_y: 0.0
    k_i_x: 0.0
    k_d_x: 0.00156
    k_d_y: 0.25
    k_heading_p: 0.06
    k_heading_d: 0.0
    max_body_x_mps: 1.0
    max_body_y_mps: 1.0
    curve: cubic_ease
  head_rack_speed:
    # Approach/REC tracking profile = 1/4 Red Area profile speed limits.
    speed_mps: 0.1
    yaw_rate_rps: 0.075
    start_radius_m: 0.0
    end_radius_m: 0.0
    min_speed_scale: 0.0
    k_p_x: 0.081
    k_p_y: 0.115
    k_i_x: 0.0
    k_i_y: 0.0
    k_d_x: 0.00156
    k_d_y: 0.25
    k_heading_p: 0.06
    k_heading_d: 0.0
    max_body_x_mps: 0.25
    max_body_y_mps: 0.25

actuators:
  arm_yaw_motor:
    type: motor
    motor_id: 5
    speed: 1.0
    positions:
      front: 0.0
      left: -1.5708
      right: 1.5708

  arm_roll_motor:
    type: motor
    motor_id: 6
    speed: 1.0
    positions:
      up: 0.0
      right_90deg: 1.5708

  arm_gripper:
    type: pneumatic
    states: [open, close]

  arm_lift:
    type: pneumatic
    states: [low, high]

  arm_stopper:
    type: pneumatic
    states: [low, high]

stages:
  - id: red_area_weapon_cycle
    type: red_area_weapon_cycle
    start_waypoint: wp_weapon_1
    slot_count: 6
    slot_spacing_m: 0.2
    slot_direction_rad: 0.0
    slot_profile: head_rack_speed
    slot_pos_tolerance: 0.005
    slot_yaw_tolerance: 0.05
    target_success_count: 5
    max_retry_per_slot: 1

    ir_topic: /arm/ir_status
    ir_field: ir
    ir_timeout_s: 0.5

    docking_torque_topic: /damiao_feedback
    docking_torque_field: motor_5_tau
    docking_torque_abs_threshold_nm: 1.3

    search:
      mode: micro_sweep_10mm
      direction_rad: 0.0
      back_distance_m: 0.01
      forward_distance_m: 0.01
      speed_mps: 0.015
      timeout_s: 2.0
      profile: head_rack_speed
      pos_tolerance: 0.003
      yaw_tolerance: 0.05

    prepare_sequence:
      - type: arm
        arm_yaw_motor: front
        arm_roll_motor: up
        arm_gripper: close
        arm_lift: low
        arm_stopper: low
      - type: wait
        duration_s: 0.10

    pickup_sequence:
      - type: arm
        arm_gripper: close
        arm_lift: low
        arm_stopper: low
      - type: wait
        duration_s: 0.15
      - type: arm
        arm_gripper: close
        arm_lift: high
        arm_stopper: low
      - type: wait
        duration_s: 0.20

    miss_sequence:
      - type: stop_chassis
      - type: arm
        arm_roll_motor: up
        arm_gripper: open
        arm_lift: low
        arm_stopper: low
      - type: wait
        duration_s: 0.15

    dock_release_sequence:
      - type: stop_chassis
      - type: arm
        arm_gripper: open
        arm_lift: high
        arm_stopper: low
      - type: wait
        duration_s: 0.15

    final_sequence:
      - type: stop_chassis
      - type: arm
        arm_yaw_motor: left
        arm_roll_motor: up
        arm_gripper: open
        arm_lift: low
        arm_stopper: low
      - type: wait
        duration_s: 0.20
      - type: stop_chassis

EOF

echo "[red_area] mission: $MISSION_FILE"
echo "[red_area] field:   $FIELD_FILE"
echo "[red_area] mirror_y: $MIRROR_Y"
echo ""

# 窗口1: 统一达妙电机驱动
gnome-terminal --geometry=100x20+0+0 -- bash -c "
source $WS/install/setup.bash
echo '=== 窗口1: damiao_ctrl (统一 CAN 电机驱动) ==='
echo 'device_id: $CHASSIS_CAN_DEVICE'
echo 'chassis control topic: /base/damiao_control'
echo 'arm control topic: /arm/damiao_ctrl'
echo 'gear_ratio: $DAMIAO_GEAR_RATIO'
echo 'Ctrl+C 退出'
echo ''
ros2 run damiao_ctrl damiao_node --ros-args \
  -p device_id:=$CHASSIS_CAN_DEVICE \
  -p chassis_control_topic:=base/damiao_control \
  -p arm_motor_ids:=[5,6] \
  -p arm_motor_modes:=[2,2] \
  -p arm_control_topic:=arm/damiao_ctrl \
  -p gear_ratio:=$DAMIAO_GEAR_RATIO
"

# 窗口2: 运动学反解
sleep 0.2
gnome-terminal --geometry=100x20+800+0 -- bash -c "
source $WS/install/setup.bash
echo '=== 窗口2: local_navigation_node (运动学反解) ==='
echo 'motor output topic: /base/damiao_control'
echo 'Ctrl+C 退出'
echo ''
ros2 run base_omniwheel_r2_600 local_navigation_node
"

# 窗口3: arm_ctrl_node
sleep 0.5
gnome-terminal --geometry=100x20+1600+0 -- bash -c "
source $WS/install/setup.bash
echo '=== 窗口3: arm_ctrl_node (M5/M6 + pneu 转发) ==='
echo 'joint input: /arm/joint_navigation'
echo 'pneu input: /arm/pneu_navigation'
echo 'motor output: /arm/damiao_ctrl'
echo 'pneu output: /arm/pneu_ctrl'
echo 'Ctrl+C 退出'
echo ''
ros2 run arm arm_ctrl_node --ros-args \
  -p joint_motor_ids:=[5,6] \
  -p joint_directions:=[1.0,1.0] \
  -p control_mode:=2 \
  -p motor_control_topic:=arm/damiao_ctrl \
  -p max_speed_rad_s:=1.0 \
  -p gear_ratio:=1.0 \
  -p max_motor_speed_rad_s:=0.0676 \
  -p republish_rate_hz:=20.0
"

# 窗口4: arm Arduino 气动桥接
sleep 0.3
gnome-terminal --geometry=100x20+1600+420 -- bash -c "
source $WS/install/setup.bash
echo '=== 窗口4: arm_arduino_node (gripper 气动桥接) ==='
echo 'port: $ARM_ARDUINO_PORT'
echo 'command topic: /arm/pneu_ctrl'
echo 'Ctrl+C 退出'
echo ''
ros2 run arm_arduino_praser arm_arduino_node --ros-args -p port:=$ARM_ARDUINO_PORT
"

# 窗口5: navigation + Arduino sensor
sleep 0.3
gnome-terminal --geometry=100x20+0+420 -- bash -c "
source $WS/install/setup.bash
echo '=== 窗口5: navigation + Arduino sensor ==='
echo '先直接发布一次 /arm/pneu_ctrl=[0,0,0]，确保 gripper/lift/stopper 初始为低状态。'
echo 'Ctrl+C 退出 (自动清理两节点)'
echo ''
sleep 1
ros2 topic pub --once /arm/pneu_ctrl std_msgs/msg/Int8MultiArray \"{data: [0, 0, 0]}\"
sleep 0.2
ros2 launch navigation navigation.launch.py mission_file:=$MISSION_FILE
"

# 窗口6: plot_debug 实时可视化（对齐 joystick.sh 的 headless 切换逻辑）
sleep 0.1
XDG_RUNTIME_DIR_VAL="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
WAYLAND_DISPLAY_VAL="${WAYLAND_DISPLAY:-wayland-0}"
gnome-terminal --geometry=100x12+0+850 -- bash -c "
source $WS/install/setup.bash
export WAYLAND_DISPLAY=\${WAYLAND_DISPLAY:-$WAYLAND_DISPLAY_VAL}
export XDG_RUNTIME_DIR=\${XDG_RUNTIME_DIR:-$XDG_RUNTIME_DIR_VAL}
export GDK_BACKEND=wayland
if [ \"$PLOT_DEBUG_HEADLESS\" = \"1\" ]; then
  unset WAYLAND_DISPLAY
  export MPLBACKEND=Agg
fi
echo '=== 窗口6: plot_debug (matplotlib 实时可视化) ==='
echo 'PLOT_DEBUG_HEADLESS: $PLOT_DEBUG_HEADLESS'
echo 'MPLBACKEND: '\$MPLBACKEND
echo 'save_dir: /home/robotics/Robocon2026_r2/log_plot_debug'
echo '关闭所有绘图窗口即退出'
echo ''
ros2 run plot_debug plot_debug_node --ros-args \
  -p show_pose2d:=false \
  -p show_target_error:=true \
  -p show_driving:=false \
  -p show_damiao:=false \
  -p show_damiao_feedback:=false \
  -p feedback_motor_ids:='[5,6]' \
  -p max_history:=$PLOT_MAX_HISTORY \
  -p update_rate_hz:=$PLOT_UPDATE_RATE_HZ \
  -p save_dir:=$PLOT_SAVE_DIR
echo ''
echo '=== plot_debug 已退出 ==='
read -p '按 Enter 关闭此窗口...'
"

echo "[red_area] 所有窗口已启动"
echo ""
echo "  窗口1: damiao_ctrl grouped damiao_node (/base/damiao_control + /arm/damiao_ctrl)"
echo "  窗口2: local_navigation_node"
echo "  窗口3: arm_ctrl_node"
echo "  窗口4: arm_arduino_node"
echo "  窗口5: navigation + Arduino sensor"
echo "  窗口6: plot_debug (matplotlib 单窗口多子图)"
echo ""
echo "  路径与动作:"
echo "    weapon1/#1: (0.350, 0.850), slots 2..6: +0.200m along waypoint yaw"
echo "    each slot: prepare -> IR/micro_sweep -> gripper close + lift high -> verify IR"
echo "    miss: lift high 后 IR=false，本 slot 最多重试 1 次；仍失败则去下一个 slot"
echo "    docking: abs(/damiao_feedback.motor_5_tau) > 1.3Nm 后 gripper open"
echo "    finish: success_count >= 5 或处理完 6 个 slot 后 stop_chassis + final safe pose"
echo ""
echo "  重点观察: /global_nav/status、/state_pose2d、/arm/ir_status、/damiao_feedback motor_5_tau"
echo "  全部退出后验证: bash $TOOLS/cleanup_ros2.sh --check"
echo ""
